
workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "dev"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never

variables:
  APP_NAME: libraskeprocessor
  APP_URL: ""

include:
  - project: 'vlibras2019/DevOps'
    ref: main
    file: '/Default-App-Pipeline-VLibras.gitlab-ci.yml'

