{{- if not .Values.externalServices.libraskeprocessor.amqp.existingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "libraskeprocessor.fullname" . }}-amqp-credentials'
  labels:
    {{ include "libraskeprocessor.labels" . | nindent 4 }}
data:
  AMQP_HOST: {{ include "libraskeprocessorGetAmqpHost" . | b64enc | quote }}
  AMQP_PASS: {{ include "libraskeprocessorGetAmqpPassword" . | b64enc | quote }}
  AMQP_PORT: {{ include "libraskeprocessorGetAmqpPort" . | b64enc | quote }}
  AMQP_USER: {{ include "libraskeprocessorGetAmqpUsername" . | b64enc | quote }}
{{- end }}
