{{- if not .Values.externalServices.libraskeapi.amqp.existingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "libraskeapi.fullname" . }}-amqp-credentials'
  labels:
    {{ include "libraskeapi.labels" . | nindent 4 }}
data:
  AMQP_HOST: {{ include "libraskeapiGetAmqpHost" . | b64enc | quote }}
  AMQP_PASS: {{ include "libraskeapiGetAmqpPassword" . | b64enc | quote }}
  AMQP_PORT: {{ include "libraskeapiGetAmqpPort" . | b64enc | quote }}
  AMQP_USER: {{ include "libraskeapiGetAmqpUsername" . | b64enc | quote }}
{{- end }}
