{{- if not .Values.libraskeprocessor.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "libraskeprocessor.fullname" . }}-app-secret'
  labels:
    {{ include "libraskeprocessor.labels" . | indent 4 }}
data:
{{- range $key, $val := .Values.libraskeprocessor.secrets.appSecret }}
  {{ $key | quote }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
