apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "libraskeapi.fullname" . | lower }}-app-config'
  labels:
    {{ include "libraskeapi.labels" . | indent 4 }}
data:
{{ range $key, $val := .Values.libraskeapi.appConfig }}
  {{ $key | quote }}:  {{ $val | quote }}
{{- end }}
