{{- if not .Values.externalServices.libraskeprocessor.postgresql.existingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "libraskeprocessor.fullname" . }}-db-credentials'
  labels:
    {{ include "libraskeprocessor.labels" . | nindent 4 }}
data:
  POSTGRES_DATABASE: {{ include "libraskeprocessorGetPostgresDatabase" . | b64enc | quote }}
  POSTGRES_USER: {{ include "libraskeprocessorGetPostgresUsername" . | b64enc | quote }}
  POSTGRES_USERNAME: {{ include "libraskeprocessorGetPostgresUsername" . | b64enc | quote }}
  POSTGRES_PASSWORD: {{ include "libraskeprocessorGetPostgresPassword" . | b64enc | quote }}
  POSTGRES_HOST: {{ include "libraskeprocessorGetPostgresHost" . | b64enc | quote }}
  POSTGRES_PORT: {{ include "libraskeprocessorGetPostgresPort" . | toString | b64enc | quote }}
{{- end }}
