{{- if not .Values.libraskeapi.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "libraskeapi.fullname" . }}-app-secret'
  labels:
    {{ include "libraskeapi.labels" . | indent 4 }}
data:
{{- range $key, $val := .Values.libraskeapi.secrets.appSecret }}
  {{ $key | quote }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
