{{- if not .Values.externalServices.libraskeapi.postgresql.existingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "libraskeapi.fullname" . }}-db-credentials'
  labels:
    {{ include "libraskeapi.labels" . | nindent 4 }}
data:
  POSTGRES_DATABASE: {{ include "libraskeapiGetPostgresDatabase" . | b64enc | quote }}
  POSTGRES_USER: {{ include "libraskeapiGetPostgresUsername" . | b64enc | quote }}
  POSTGRES_USERNAME: {{ include "libraskeapiGetPostgresUsername" . | b64enc | quote }}
  POSTGRES_PASSWORD: {{ include "libraskeapiGetPostgresPassword" . | b64enc | quote }}
  POSTGRES_HOST: {{ include "libraskeapiGetPostgresHost" . | b64enc | quote }}
  POSTGRES_PORT: {{ include "libraskeapiGetPostgresPort" . | toString | b64enc | quote }}
{{- end }}
